import { useCallback, useState } from "react";
import { AnimatePresence } from "framer-motion";
import { Link } from "react-router-dom";
import AmbientField from "../components/AmbientField";
import Landing from "./Landing";
import FieldStep from "./FieldStep";
import InterestStep from "./InterestStep";
import HorizonStep from "./HorizonStep";
import GeneratingScreen from "./GeneratingScreen";
import ResultPage from "./ResultPage";
import { generateResearchQuestion } from "../lib/generator";

const STAGES = {
  LANDING: "landing",
  FIELD: "field",
  INTEREST: "interest",
  HORIZON: "horizon",
  GENERATING: "generating",
  RESULT: "result",
  ERROR: "error",
};

export default function WizardApp() {
  const [stage, setStage] = useState(STAGES.LANDING);
  const [fieldId, setFieldId] = useState(null);
  const [interest, setInterest] = useState("");
  const [horizonYear, setHorizonYear] = useState(null);
  const [ambitionBoost, setAmbitionBoost] = useState(0);
  const [result, setResult] = useState(null);
  const [toast, setToast] = useState(null);
  const [errorMsg, setErrorMsg] = useState(null);

  const runGeneration = useCallback((boost = 0) => {
    setAmbitionBoost(boost);
    setStage(STAGES.GENERATING);
  }, []);

  const handleGenerationDone = useCallback(async () => {
    try {
      const data = await generateResearchQuestion({
        fieldId,
        interest,
        horizonYear,
        ambitionBoost,
      });
      setResult(data);
      setStage(STAGES.RESULT);
    } catch (err) {
      console.error("Generation failed:", err);
      setErrorMsg("Could not reach the AI backend. Check your Cloudflare Worker URL in src/lib/generator.js and try again.");
      setStage(STAGES.ERROR);
    }
  }, [fieldId, interest, horizonYear, ambitionBoost]);

  const handleAnother = () => { runGeneration(0); };
  const handleMoreAmbitious = () => { runGeneration(ambitionBoost + 1); };

  const handleShare = async () => {
    const text = result
      ? `${result.question}\n\nGenerated by Research Question Generator 2040`
      : "Research Question Generator 2040";
    try {
      if (navigator.share) {
        await navigator.share({ title: "Research Question Generator 2040", text });
      } else {
        await navigator.clipboard.writeText(text);
        setToast("Copied to clipboard");
        setTimeout(() => setToast(null), 2000);
      }
    } catch {
      // user cancelled share sheet — no-op
    }
  };

  const goBack = (target) => setStage(target);

  return (
    <div className="relative min-h-[100dvh] bg-void font-body text-ink">
      <AmbientField density={stage === STAGES.RESULT ? 10 : 18} />

      <AnimatePresence mode="wait">
        {stage === STAGES.LANDING && (
          <Landing key="landing" onStart={() => setStage(STAGES.FIELD)} />
        )}

        {stage === STAGES.FIELD && (
          <FieldStep
            key="field"
            value={fieldId}
            onSelect={(id) => {
              setFieldId(id);
              setStage(STAGES.INTEREST);
            }}
            onBack={() => goBack(STAGES.LANDING)}
          />
        )}

        {stage === STAGES.INTEREST && (
          <InterestStep
            key="interest"
            value={interest}
            onChange={setInterest}
            onNext={() => setStage(STAGES.HORIZON)}
            onBack={() => goBack(STAGES.FIELD)}
          />
        )}

        {stage === STAGES.HORIZON && (
          <HorizonStep
            key="horizon"
            value={horizonYear}
            onSelect={(year) => {
              setHorizonYear(year);
              runGeneration(0);
            }}
            onBack={() => goBack(STAGES.INTEREST)}
          />
        )}

        {stage === STAGES.GENERATING && (
          <GeneratingScreen key="generating" onDone={handleGenerationDone} />
        )}

        {stage === STAGES.RESULT && (
          <ResultPage
            key="result"
            result={result}
            onAnother={handleAnother}
            onMoreAmbitious={handleMoreAmbitious}
            onShare={handleShare}
          />
        )}

        {stage === STAGES.ERROR && (
          <div key="error" className="flex min-h-[100dvh] flex-col items-center justify-center gap-6 px-6 text-center">
            <p className="font-mono text-xs uppercase tracking-widest text-red-400">Generation Failed</p>
            <p className="max-w-sm text-sm text-ink-muted">{errorMsg}</p>
            <button
              onClick={() => setStage(STAGES.LANDING)}
              className="glass-pill px-6 py-3 font-mono text-xs uppercase tracking-widest text-ink transition-colors hover:text-signal"
            >
              Try Again
            </button>
          </div>
        )}
      </AnimatePresence>

      {toast && (
        <div className="fixed bottom-24 left-1/2 z-30 -translate-x-1/2 rounded-full bg-void-raised px-4 py-2 font-mono text-xs text-ink shadow-panel">
          {toast}
        </div>
      )}

      {stage === STAGES.LANDING && (
        <Link
          to="/presentation"
          className="fixed bottom-3 right-3 z-30 font-mono text-[10px] text-ink-faint/40 transition-colors hover:text-ink-faint"
          aria-label="Presentation mode"
        >
          ·
        </Link>
      )}
    </div>
  );
}
